### Data Encoding
Data encoding is the process of converting categorical data into a numerical format that can be used by machine learning algorithms. This is necessary because most machine learning models require numerical input. There are several techniques for data encoding, including:

Nominal / One-Hot Encoding: This technique is used for categorical variables that do not have an inherent order. It creates a new binary column for each category, where the value is 1 if the category is present and 0 otherwise. Sparse matrix causes overfitting and high dimensionality.
   Red : [1,0,0]
   Green : [0,1,0]
    Blue : [0,0,1]



In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [2]:
df = pd.DataFrame({
    'color': ['red','blue','green','yellow','purple','red','green']
})

In [3]:
df.head()

,color
0,red
1,blue
2,green
3,yellow
4,purple


In [4]:
## Create and instance of one hot encoder

encoder = OneHotEncoder()


In [5]:
## perform fit and transform

encoded_data  = encoder.fit_transform(df[['color']]).toarray() # type: ignore

In [6]:
import pandas as pd
encoder_df = pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out())

In [7]:
encoder_df

,color_blue,color_green,color_purple,color_red,color_yellow
0,0.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0
6,0.0,1.0,0.0,0.0,0.0


In [8]:
# for new data
encoder.transform([['blue']]).toarray()

/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0., 0., 0.]])

In [9]:
pd.concat([df,encoder_df],axis=1)

,color,color_blue,color_green,color_purple,color_red,color_yellow
0,red,0.0,0.0,0.0,1.0,0.0
1,blue,1.0,0.0,0.0,0.0,0.0
2,green,0.0,1.0,0.0,0.0,0.0
3,yellow,0.0,0.0,0.0,0.0,1.0
4,purple,0.0,0.0,1.0,0.0,0.0
5,red,0.0,0.0,0.0,1.0,0.0
6,green,0.0,1.0,0.0,0.0,0.0


In [10]:
import seaborn as sns
tips_data = sns.load_dataset('tips')

In [11]:
tips_data

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [12]:
## Encoding

encoder = OneHotEncoder()

In [13]:
tips_encoded_data = encoder.fit_transform(tips_data[['sex','smoker','day','time']]).toarray()

In [14]:
import pandas as pd
tips_encoded_df = pd.DataFrame(tips_encoded_data,columns=encoder.get_feature_names_out())

In [15]:
tips_encoded_df

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0


### Label Encoding

Label / Ordinal Encoding: This technique is used for categorical variables that have an inherent order. It assigns a unique integer to each category based on their order. It assigns unique integer to each category based on their order. For example, if we have a categorical variable "Size" with categories "Small", "Medium", and "Large", we can assign the following integers:
Small : 1
Medium : 2
Large : 3

In [16]:
df = pd.DataFrame({
    'color': ['red','blue','green','yellow','purple','red','green']
})

In [17]:
df

,color
0,red
1,blue
2,green
3,yellow
4,purple
5,red
6,green


In [18]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [19]:
lbl_encoder.fit_transform(df[['color']])

/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([3, 0, 1, 4, 2, 3, 1])

In [20]:
lbl_encoder.transform([['red']])

/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([3])

In [21]:
lbl_encoder.transform([['blue']])

/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

### Ordinal Encoding
Ordinal Encoding: This technique is used for categorical variables that have an inherent order. It assigns a unique integer to each category based on their order. For example, if we have a categorical variable "Size" with categories "Small", "Medium", and "Large", we can assign the following integers:
Small : 1
Medium : 2
Large : 3

In [22]:
from sklearn.preprocessing import OrdinalEncoder


In [23]:
size = pd.DataFrame({
    'size':['extra-small','small','medium','large','extra-large','small','large']
})

In [24]:
size

,size
0,extra-small
1,small
2,medium
3,large
4,extra-large
5,small
6,large


In [25]:
ord_encoder = OrdinalEncoder(categories=[['extra-small','small','medium','large','extra-large']])

In [26]:
ord_encoder.fit_transform(size[['size']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [1.],
       [3.]])

In [27]:
ord_encoder.transform([['extra-large']])

/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[4.]])

### Target Guided ordinal encoding:
 This technique is used for categorical variables that have an inherent order and are related to the target variable. It assigns a unique integer to each category based on the mean of the target variable for that category.
 Example : If we have a categorical variable "Education Level" with categories "High School", "Bachelor's", and "Master's", and the target variable is "Income", we can calculate the mean income for each education level and assign integers based on the mean income:
High School : 1 (mean income = $30,000)
Bachelor's : 2 (mean income = $50,000)
Master's : 3 (mean income = $70,000)

In [28]:
import pandas as pd

df  = pd.DataFrame({
    'city': ['Bangalore','Chennai','Bangalore','New Delhi','Mumbai'],
    'price':[200,150,300,250,180]
})

In [29]:
df

,city,price
0,Bangalore,200
1,Chennai,150
2,Bangalore,300
3,New Delhi,250
4,Mumbai,180


In [30]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [31]:
mean_price

{'Bangalore': 250.0, 'Chennai': 150.0, 'Mumbai': 180.0, 'New Delhi': 250.0}

In [32]:
df['city_encoded'] = df['city'].map(mean_price)

In [33]:
df

,city,price,city_encoded
0,Bangalore,200,250.0
1,Chennai,150,150.0
2,Bangalore,300,250.0
3,New Delhi,250,250.0
4,Mumbai,180,180.0


In [34]:
df[['price','city_encoded']]

,price,city_encoded
0,200,250.0
1,150,150.0
2,300,250.0
3,250,250.0
4,180,180.0


In [35]:
import seaborn as sns
tips = sns.load_dataset('tips')

In [36]:
tips

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [37]:
tips[['total_bill','time']]

,total_bill,time
0,16.99,Dinner
1,10.34,Dinner
2,21.01,Dinner
3,23.68,Dinner
4,24.59,Dinner
...,...,...
239,29.03,Dinner
240,27.18,Dinner
241,22.67,Dinner
242,17.82,Dinner


In [38]:
mean_bill = tips.groupby('time')['total_bill'].mean().to_dict()

In [39]:
mean_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [40]:
tips['time_encoded'] = tips['time'].map(mean_bill)

In [41]:
tips[['total_bill','time_encoded','time']]

,total_bill,time_encoded,time
0,16.99,20.797159,Dinner
1,10.34,20.797159,Dinner
2,21.01,20.797159,Dinner
3,23.68,20.797159,Dinner
4,24.59,20.797159,Dinner
...,...,...,...
239,29.03,20.797159,Dinner
240,27.18,20.797159,Dinner
241,22.67,20.797159,Dinner
242,17.82,20.797159,Dinner


## From-scratch: manual one-hot encoding

`pd.get_dummies` and `OneHotEncoder` both do the same mechanical thing: for each distinct
category, create a binary column that is `1` where the row has that category and `0` everywhere
else. The cell below builds those columns by hand with a plain Python loop over the unique
categories — no encoding library call — then checks the result against both `pd.get_dummies` and
`sklearn.preprocessing.OneHotEncoder` on the identical data.

In [42]:
import numpy as np


def manual_one_hot(series: pd.Series) -> pd.DataFrame:
    """Build one binary column per distinct category, by hand, with no encoding library call."""
    categories = sorted(series.unique())
    columns = {}
    for cat in categories:
        columns[f"{series.name}_{cat}"] = (series == cat).astype(float)
    return pd.DataFrame(columns, index=series.index)


color_df = pd.DataFrame({'color': ['red', 'blue', 'green', 'yellow', 'purple', 'red', 'green']})

manual_encoded = manual_one_hot(color_df['color'])
dummies_encoded = pd.get_dummies(color_df['color'], prefix='color').astype(float)

sk_encoder = OneHotEncoder()
sk_encoded = pd.DataFrame(
    sk_encoder.fit_transform(color_df[['color']]).toarray(),
    columns=sk_encoder.get_feature_names_out(),
)

print(manual_encoded)
print()
print("manual vs pd.get_dummies match:", (manual_encoded.values == dummies_encoded[manual_encoded.columns].values).all())
print("manual vs sklearn OneHotEncoder match:", np.allclose(manual_encoded.values, sk_encoded.values))


   color_blue  color_green  color_purple  color_red  color_yellow
0         0.0          0.0           0.0        1.0           0.0
1         1.0          0.0           0.0        0.0           0.0
2         0.0          1.0           0.0        0.0           0.0
3         0.0          0.0           0.0        0.0           1.0
4         0.0          0.0           1.0        0.0           0.0
5         0.0          0.0           0.0        1.0           0.0
6         0.0          1.0           0.0        0.0           0.0

manual vs pd.get_dummies match: True
manual vs sklearn OneHotEncoder match: True


## Failure mode 1: high-cardinality columns explode dimensionality

One-hot encoding creates one column per distinct category. That's fine for `color` (5 categories)
or `day` (4 categories) — it's a problem for a column like a ZIP code or a user ID, where the
number of distinct values can be in the thousands. The cell below one-hot-encodes a synthetic
5-digit ZIP code column and measures the resulting shape and memory footprint directly.

In [43]:
rng = np.random.default_rng(0)
n_rows = 5000
zip_codes = rng.integers(10000, 99999, size=n_rows).astype(str)
zip_df = pd.DataFrame({'zip': zip_codes})

zip_dummies = pd.get_dummies(zip_df['zip'], prefix='zip')

print(f"Rows: {n_rows}   Distinct ZIP codes: {zip_df['zip'].nunique()}")
print(f"One-hot encoded shape: {zip_dummies.shape}  (one column per distinct ZIP code)")
print(f"Memory footprint of the one-hot matrix: {zip_dummies.memory_usage(deep=True).sum() / 1e6:.2f} MB")
print(f"Memory footprint of the original single column: {zip_df.memory_usage(deep=True)['zip'] / 1e6:.4f} MB")


Rows: 5000   Distinct ZIP codes: 4887
One-hot encoded shape: (5000, 4887)  (one column per distinct ZIP code)
Memory footprint of the one-hot matrix: 24.44 MB
Memory footprint of the original single column: 0.0650 MB


## Failure mode 2: unseen categories at inference time

A fitted `OneHotEncoder` only knows the categories it saw during `.fit(...)`. A category that
shows up later — at inference/production time — that was never in the training data has nowhere
to go. By default this is a hard error, not a silent guess.

In [44]:
strict_encoder = OneHotEncoder()  # default: handle_unknown='error'
strict_encoder.fit(color_df[['color']])

try:
    strict_encoder.transform([['black']])  # 'black' was never seen during fit
except ValueError as exc:
    print("Fitted encoder rejects an unseen category:")
    print(" ", exc)

print()

# The fix: explicitly opt into a defined fallback for unseen categories
tolerant_encoder = OneHotEncoder(handle_unknown='ignore')
tolerant_encoder.fit(color_df[['color']])
unseen_result = tolerant_encoder.transform([['black']]).toarray()
print("With handle_unknown='ignore', an unseen category encodes to all zeros:")
print(" ", unseen_result, " columns:", list(tolerant_encoder.get_feature_names_out()))


Fitted encoder rejects an unseen category:
  Found unknown categories ['black'] in column 0 during transform

With handle_unknown='ignore', an unseen category encodes to all zeros:
  [[0. 0. 0. 0. 0.]]  columns: ['color_blue', 'color_green', 'color_purple', 'color_red', 'color_yellow']


/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/home/yashwanth-aravind/ml-course/python-bootcamp/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
