# NumPy — Numerical Computing in Python

NumPy is the foundation of scientific computing in Python. Nearly every ML/DS library (Pandas, scikit-learn, TensorFlow, PyTorch) is built on top of it.

**Why NumPy over plain Python lists?**
- Vectorised operations — no Python `for` loops needed
- Broadcasting — automatic shape alignment
- ~100× faster than lists for numerical work
- Foundation for all ML libraries

Topics:
- Array creation
- Array attributes and inspection
- Indexing & slicing
- Vectorised operations & broadcasting
- Aggregation functions
- Reshaping & stacking
- Linear algebra
- Random number generation

In [1]:
import numpy as np
print(np.__version__)

2.4.4


## 1. Array Creation

In [2]:
# From Python lists
a1 = np.array([1, 2, 3, 4, 5])             # 1-D
a2 = np.array([[1, 2, 3], [4, 5, 6]])       # 2-D
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3-D

print(a1)
print(a2)
print(a3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Built-in constructors
print(np.zeros((3, 4)))          # all zeros
print(np.ones((2, 3)))           # all ones
print(np.full((3, 3), 7))        # fill with value
print(np.eye(4))                 # identity matrix
print(np.arange(0, 20, 3))       # like range — start, stop, step
print(np.linspace(0, 1, 6))      # 6 evenly spaced from 0 to 1 (inclusive)
print(np.empty((2, 2)))          # uninitialised (fast, but values undefined)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0  3  6  9 12 15 18]
[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 1.]
 [1. 1.]]


In [4]:
# Data types — choosing the right dtype saves memory
print(np.array([1.5, 2.5], dtype=np.float32))   # 32-bit float
print(np.array([1, 2, 3], dtype=np.int8))        # 8-bit int (saves memory)
print(np.zeros(5, dtype=bool))                   # boolean array

# Type casting
arr = np.array([1.7, 2.9, 3.1])
print(arr.astype(int))   # truncates (does not round)

[1.5 2.5]
[1 2 3]
[False False False False False]
[1 2 3]


## 2. Array Attributes

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('shape  :', arr.shape)      # (rows, cols)
print('ndim   :', arr.ndim)       # number of dimensions
print('size   :', arr.size)       # total elements
print('dtype  :', arr.dtype)      # data type
print('nbytes :', arr.nbytes)     # memory in bytes
print('itemsize:', arr.itemsize)  # bytes per element

shape  : (3, 3)
ndim   : 2
size   : 9
dtype  : int64
nbytes : 72
itemsize: 8


## 3. Indexing & Slicing

NumPy indexing: `arr[row, col]`  (or `arr[row][col]` — same result, less efficient)

In [6]:
# 1-D indexing
a = np.arange(10)
print(a[3])       # 3
print(a[-1])      # 9  (last)
print(a[2:7])     # [2 3 4 5 6]
print(a[::2])     # every other: [0 2 4 6 8]
print(a[::-1])    # reversed

3
9
[2 3 4 5 6]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [7]:
# 2-D indexing
m = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(m[0, 2])       # 3  — row 0, col 2
print(m[1, :])       # [4 5 6]  — entire row 1
print(m[:, 2])       # [3 6 9]  — entire col 2
print(m[0:2, 1:])    # top-right 2×2 block
print(m[[0,2], :])   # fancy indexing — rows 0 and 2

3
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]
[[1 2 3]
 [7 8 9]]


In [8]:
# Boolean (mask) indexing — used everywhere in ML
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(mask)        # [False False  True  True  True]
print(arr[mask])   # [30 40 50]

# Inline
print(arr[arr % 20 == 0])   # [20 40]

# Updating with a mask
arr[arr < 25] = 0
print(arr)   # [0 0 30 40 50]

[False False  True  True  True]
[30 40 50]
[20 40]
[ 0  0 30 40 50]


## 4. Vectorised Operations

Operations apply **element-wise** — no loops needed. This is what makes NumPy fast.

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise arithmetic
print(a + b)    # [11 22 33 44]
print(a * b)    # [10 40 90 160]
print(a ** 2)   # [ 1  4  9 16]
print(b / a)    # [10. 10. 10. 10.]

# Universal functions (ufuncs)
print(np.sqrt(b))
print(np.exp(a))
print(np.log(b))
print(np.sin(np.linspace(0, np.pi, 5)))

[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
[10. 10. 10. 10.]
[3.16227766 4.47213595 5.47722558 6.32455532]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[2.30258509 2.99573227 3.40119738 3.68887945]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


## 5. Broadcasting

Broadcasting lets NumPy operate on arrays with **different shapes** by automatically expanding the smaller one.

Rule: two dimensions are compatible if they are equal OR one of them is 1.

In [10]:
# Scalar broadcast — applies to every element
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr * 10)     # multiply every element by 10
print(arr + 100)

# Row vector broadcast to matrix
row = np.array([1, 2, 3])    # shape (3,)
print(arr + row)              # adds row to each row of arr

# Column vector broadcast
col = np.array([[10], [20]]) # shape (2,1)
print(arr + col)              # adds 10 to row 0, 20 to row 1

[[10 20 30]
 [40 50 60]]
[[101 102 103]
 [104 105 106]]
[[2 4 6]
 [5 7 9]]
[[11 12 13]
 [24 25 26]]


In [11]:
# Practical: feature normalisation (Z-score)
data = np.array([[2.0, 1.0, 5.0],
                 [1.0, 3.0, 2.0],
                 [4.0, 2.0, 3.0]])

mean = data.mean(axis=0)   # column means
std  = data.std(axis=0)    # column stds
normalised = (data - mean) / std
print(normalised.round(3))
print('Column means after normalisation:', normalised.mean(axis=0).round(10))

[[-0.267 -1.225  1.336]
 [-1.069  1.225 -1.069]
 [ 1.336  0.    -0.267]]
Column means after normalisation: [-0.  0. -0.]


## 6. Aggregation Functions

In [12]:
arr = np.array([[4, 2, 7], [1, 9, 3], [6, 5, 8]])

print('sum    (all) :', arr.sum())
print('sum    (col) :', arr.sum(axis=0))    # sum of each column
print('sum    (row) :', arr.sum(axis=1))    # sum of each row
print('mean         :', arr.mean())
print('std          :', arr.std())
print('min / max    :', arr.min(), arr.max())
print('argmin/argmax:', arr.argmin(), arr.argmax())  # flat index
print('cumsum       :', arr.cumsum())       # running sum
print('median       :', np.median(arr))
print('percentile 75:', np.percentile(arr, 75))

sum    (all) : 45
sum    (col) : [11 16 18]
sum    (row) : [13 13 19]
mean         : 5.0
std          : 2.581988897471611
min / max    : 1 9
argmin/argmax: 3 4
cumsum       : [ 4  6 13 14 23 26 32 37 45]
median       : 5.0
percentile 75: 7.0


## 7. Reshaping, Stacking & Splitting

In [13]:
a = np.arange(12)
print(a)

print(a.reshape(3, 4))     # reshape to 3×4
print(a.reshape(2, 2, 3))  # reshape to 3-D
print(a.reshape(-1, 3))    # -1 means 'figure it out' → (4, 3)

b = a.reshape(3, 4)
print(b.flatten())         # always returns a copy
print(b.ravel())           # returns view when possible (faster)
print(b.T)                 # transpose

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [14]:
# Stacking arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack([a, b]))   # vertical stack  → 2×3
print(np.hstack([a, b]))   # horizontal stack → 1×6
print(np.stack([a, b]))    # new axis → 2×3
print(np.concatenate([a, b]))  # flat join

# Splitting
m = np.arange(1, 13).reshape(4, 3)
parts = np.vsplit(m, 2)    # split into 2 equal parts vertically
print(parts[0])
print(parts[1])

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## 8. Linear Algebra

Linear algebra is the language of ML — matrix multiplication, inverses, and eigendecomposition underlie most algorithms.

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print('Element-wise *:', A * B)
print('Matrix mul @:  ', A @ B)           # matrix multiplication
print('np.dot:        ', np.dot(A, B))    # same as @

print('Transpose:     ', A.T)
print('Determinant:   ', np.linalg.det(A))
print('Inverse:       ', np.linalg.inv(A))
print('A @ inv(A):\n', (A @ np.linalg.inv(A)).round(10))  # identity

Element-wise *: [[ 5 12]
 [21 32]]
Matrix mul @:   [[19 22]
 [43 50]]
np.dot:         [[19 22]
 [43 50]]
Transpose:      [[1 3]
 [2 4]]
Determinant:    -2.0000000000000004
Inverse:        [[-2.   1. ]
 [ 1.5 -0.5]]
A @ inv(A):
 [[1. 0.]
 [0. 1.]]


In [16]:
# Eigenvalues & eigenvectors (key for PCA)
M = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(M)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors:\n', eigenvectors)

# Solve linear system Ax = b
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print('Solution x:', x)
print('Verify A@x:', A @ x)    # should equal b

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
Solution x: [2. 3.]
Verify A@x: [9. 8.]


## 9. Random Number Generation

In [17]:
rng = np.random.default_rng(seed=42)  # reproducible RNG (modern API)

print(rng.random((3, 3)))           # uniform [0, 1)
print(rng.integers(0, 10, size=5))  # random ints in [0, 10)
print(rng.normal(0, 1, size=5))     # Gaussian (mean=0, std=1)
print(rng.choice([1,2,3,4,5], size=3, replace=False))  # sample without replacement

# Shuffle
arr = np.arange(10)
rng.shuffle(arr)
print(arr)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
[8 4 5 3 1]
[ 0.0660307   1.12724121  0.46750934 -0.85929246  0.36875078]
[3 4 1]
[2 8 9 7 4 1 6 3 5 0]


## 10. Performance: NumPy vs. Python

This is why we use NumPy — not just convenience, but speed.

In [18]:
import time

n = 1_000_000

# Pure Python
python_list = list(range(n))
start = time.perf_counter()
result_py = [x**2 for x in python_list]
time_py = time.perf_counter() - start

# NumPy
np_array = np.arange(n)
start = time.perf_counter()
result_np = np_array ** 2
time_np = time.perf_counter() - start

print(f'Python: {time_py:.4f}s')
print(f'NumPy:  {time_np:.6f}s')
print(f'NumPy is {time_py/time_np:.0f}x faster')

Python: 0.0660s
NumPy:  0.003170s
NumPy is 21x faster


## 11. Broadcasting Rules — Derived From Shape Arithmetic

Section 5 stated the rule ("dimensions are compatible if equal or one is 1"). Here it's derived
from actual shape arithmetic, not just asserted.

NumPy compares two shapes **from the trailing (rightmost) dimension leftward**. For each aligned
pair of dimensions:
- if they're equal → keep that size
- if one of them is `1` → stretch it to match the other
- otherwise → incompatible, raise an error

Missing leading dimensions are treated as `1`. Walking through `(3,1)` and `(1,4)`:

```
shape a: (3, 1)
shape b:    (1, 4)      <- align from the right
```
- Rightmost pair: `1` vs `4` → one of them is 1 → stretch to `4`
- Next pair: `3` vs `1` → one of them is 1 → stretch to `3`
- Result shape: `(3, 4)`

`a`'s single column is repeated across 4 columns; `b`'s single row is repeated across 3 rows —
every `(i, j)` cell becomes `a[i, 0] + b[0, j]`. This is why a `(3,1)` column vector plus a `(1,4)`
row vector produces a full `(3,4)` outer-sum table below.

In [19]:
a = np.arange(3).reshape(3, 1)   # shape (3,1) — a column vector
b = np.arange(4).reshape(1, 4)   # shape (1,4) — a row vector
c = a + b
print('a shape:', a.shape, ' b shape:', b.shape, ' result shape:', c.shape)
print(c)

# When shapes are NOT compatible: no dimension is 1 and they're not equal
try:
    x = np.zeros((2, 3))
    y = np.zeros((2,))     # shape (2,) aligns against x's trailing dim (3) — 2 != 3 and neither is 1
    x + y
except ValueError as e:
    print('ValueError:', e)

a shape: (3, 1)  b shape: (1, 4)  result shape: (3, 4)
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
ValueError: operands could not be broadcast together with shapes (2,3) (2,) 


## 12. From-Scratch: Manual Element-Wise Loop vs. Vectorized NumPy

Section 10 already timed `x**2` (list comprehension) against `arr**2`. Here the "from-scratch"
version is a literal, explicit `for` loop over indices — no list comprehension, no `zip` — computing
the same real, non-trivial expression as the vectorized NumPy call, on the same random data.

In [20]:
n = 2_000_000
rng = np.random.default_rng(0)
a1 = rng.random(n)
b1 = rng.random(n)

# Manual, from-scratch element-wise loop: c[i] = a[i]*b[i] + a[i]**2
start = time.perf_counter()
result_manual = [0.0] * n
for i in range(n):
    result_manual[i] = a1[i] * b1[i] + a1[i] ** 2
t_manual = time.perf_counter() - start

# Vectorized NumPy equivalent, same data, same expression
start = time.perf_counter()
result_vec = a1 * b1 + a1 ** 2
t_vec = time.perf_counter() - start

print(f'Manual Python loop:  {t_manual:.4f}s')
print(f'Vectorized NumPy:    {t_vec:.6f}s')
print(f'NumPy is {t_manual / t_vec:.1f}x faster')
print('Results match:', np.allclose(np.array(result_manual), result_vec))

Manual Python loop:  0.4148s
Vectorized NumPy:    0.014581s
NumPy is 28.4x faster
Results match: True


## 13. Failure Modes

**Accidental broadcasting — wrong shape, no error, silently wrong answer.** Subtracting a
per-row mean from a matrix requires reshaping the 1-D mean vector into a column `(n, 1)` first.
Forgetting that reshape doesn't raise an error when the matrix happens to be square — NumPy just
broadcasts the vector as a *row* instead of a *column*, silently computing the wrong thing.

In [21]:
# 4 students x 4 assignment grades — intent: subtract each student's own row mean
grades = np.array([[70., 80., 90., 60.],
                    [50., 60., 70., 80.],
                    [90., 95., 85., 80.],
                    [40., 55., 65., 70.]])
row_means = grades.mean(axis=1)   # shape (4,)  — one mean per student
print('row_means shape:', row_means.shape)

# BUG: grades is (4,4) and row_means is (4,) — broadcasting aligns (4,) against the
# trailing dimension (columns), so this subtracts a *per-column* value from every row,
# not each student's own row mean. Shapes are "compatible", so NO error is raised.
wrong = grades - row_means
print('wrong shape:', wrong.shape, '(matches grades.shape — looks fine at a glance!)')
print(wrong)
print('row 0 sums to (should be ~0 for a correct row-centering):', wrong[0].sum())

# FIX: reshape to a column vector (4,1) so broadcasting aligns per-row, not per-column
correct = grades - row_means.reshape(-1, 1)
print(correct)
print('row 0 sums to (correctly ~0):', correct[0].sum())

row_means shape: (4,)
wrong shape: (4, 4) (matches grades.shape — looks fine at a glance!)
[[ -5.   15.    2.5   2.5]
 [-25.   -5.  -17.5  22.5]
 [ 15.   30.   -2.5  22.5]
 [-35.  -10.  -22.5  12.5]]
row 0 sums to (should be ~0 for a correct row-centering): 15.0
[[ -5.    5.   15.  -15. ]
 [-15.   -5.    5.   15. ]
 [  2.5   7.5  -2.5  -7.5]
 [-17.5  -2.5   7.5  12.5]]
row 0 sums to (correctly ~0): 0.0


**Views vs. copies — mutating a view unexpectedly changes the original array.** Basic slicing
(`arr[a:b]`) returns a **view** — it shares memory with the original array. Fancy indexing
(a list/array of indices, or a boolean mask) always returns a **copy**. Mixing these up is a
common, silent source of bugs: mutating what you think is an independent array actually mutates
data other code still holds a reference to.

In [22]:
# Basic slicing -> a VIEW (shares memory)
arr = np.arange(10)
view = arr[2:5]
view[0] = 99
print('basic slice is a view — mutating it changed the original:', arr)

# .copy() breaks that link
arr2 = np.arange(10)
copy = arr2[2:5].copy()
copy[0] = -1
print('explicit .copy() is independent — original unaffected:', arr2)

# Fancy indexing (list of indices) -> always a COPY, even without .copy()
arr3 = np.arange(10)
fancy = arr3[[2, 3, 4]]
fancy[0] = -50
print('fancy indexing already copies — original unaffected:', arr3)

print('arr.base is arr (owns its data):', arr.base is None)
print('view.base is arr (view shares memory with arr):', view.base is arr)

basic slice is a view — mutating it changed the original: [ 0  1 99  3  4  5  6  7  8  9]
explicit .copy() is independent — original unaffected: [0 1 2 3 4 5 6 7 8 9]
fancy indexing already copies — original unaffected: [0 1 2 3 4 5 6 7 8 9]
arr.base is arr (owns its data): True
view.base is arr (view shares memory with arr): True


## Quick Summary

| Operation | Code |
|-----------|------|
| Create array | `np.array(...)`, `np.zeros`, `np.arange`, `np.linspace` |
| Inspect | `.shape`, `.dtype`, `.ndim`, `.size` |
| Index | `arr[row, col]`, `arr[mask]` |
| Math | `arr + arr`, `np.sqrt`, `np.exp`, `@` |
| Aggregate | `.sum()`, `.mean()`, `.std()`, `.argmax()` |
| Reshape | `.reshape()`, `.flatten()`, `.T` |
| Stack | `np.vstack`, `np.hstack`, `np.concatenate` |
| Linalg | `np.linalg.dot`, `.inv`, `.eig`, `.solve` |

**Next →** [02 – Pandas](../02-pandas/)